#!/bin/bash

#############################################################################
#  Psiphon Multi-Instance Deployment Manager v2.2
#  Part of X-UI-PRO - Multi-Country VPN Configuration System
#  
#  Deploys up to 10 concurrent Psiphon instances using Environment Files
#  Standardized configuration based on bepass-org/warp-plus documentation
#############################################################################

set -eo pipefail

# Colors
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[0;33m'
readonly BLUE='\033[0;34m'
readonly CYAN='\033[0;36m'
readonly BOLD='\033[1m'
readonly NC='\033[0m'

# Configuration
readonly WARP_DIR="/etc/warp-plus"
readonly WARP_BIN="$WARP_DIR/warp-plus"
readonly CONFIG_DIR="/etc/psiphon"
readonly LOG_DIR="/var/log/psiphon"
readonly SYSTEMD_DIR="/etc/systemd/system"
readonly MASTER_CONFIG="${CONFIG_DIR}/manager_config.json"

# Valid countries list from official documentation
readonly VALID_COUNTRIES="AT AU BE BG CA CH CZ DE DK EE ES FI FR GB HR HU IE IN IT JP LV NL NO PL PT RO RS SE SG SK US"

# Dependencies
check_dependencies() {
    local deps=(wget unzip curl jq shuf)
    local install_list=()
    for dep in "${deps[@]}"; do
        if ! command -v "$dep" &> /dev/null; then
            install_list+=("$dep")
        fi
    done
    
    if [[ ${#install_list[@]} -gt 0 ]]; then
        echo -e "${YELLOW}Installing missing dependencies: ${install_list[*]}${NC}"
        if command -v apt &> /dev/null; then
            apt update -qq && apt install -y -qq "${install_list[@]}"
        elif command -v dnf &> /dev/null; then
            dnf install -y -q "${install_list[@]}"
        fi
    fi
}

# Install Warp-Plus
install_warp_plus() {
    if [[ ! -f "$WARP_BIN" ]]; then
        echo -e "${BLUE}Installing warp-plus...${NC}"
        mkdir -p "$WARP_DIR"
        local ARCH=$(uname -m)
        local BASE_URL="https://github.com/bepass-org/warp-plus/releases/latest/download/warp-plus_linux"
        local ZIP_URL=""
        
        case "$ARCH" in
            x86_64|amd64) ZIP_URL="${BASE_URL}-amd64.zip" ;;
            aarch64|arm64) ZIP_URL="${BASE_URL}-arm64.zip" ;;
            *) echo -e "${RED}Unsupported architecture: $ARCH${NC}"; exit 1 ;;
        esac
        
        wget -qO "/tmp/warp.zip" "$ZIP_URL"
        unzip -qo "/tmp/warp.zip" -d "$WARP_DIR"
        chmod +x "$WARP_BIN"
        rm -f "/tmp/warp.zip"
        echo -e "${GREEN}warp-plus installed.${NC}"
    fi
}

# Detect Server Country
get_server_country() {
    curl -s --connect-timeout 5 https://ipapi.co/country_code 2>/dev/null || echo "XX"
}

# Generate Environment File
create_env_file() {
    local port="$1"
    local country="$2"
    local cache_dir="/var/cache/psiphon-${port}"
    local env_file="${CONFIG_DIR}/psiphon-${port}.env"
    
    mkdir -p "$cache_dir"
    
    # Create configuration environment file
    # This aligns with "using doc" by explicitly setting flags in a structured way
    cat > "$env_file" << EOF
# Psiphon Instance Configuration - Port $port
# Generated by X-UI-PRO

# General Settings
PORT=$port
COUNTRY=$country
CACHE_DIR=$cache_dir

# Command Line Arguments
# --cfon: Enable Psiphon mode (Pure Psiphon, no WARP scanning)
# --country: Target country code
# --bind: SOCKS5 bind address
# --cache-dir: Persistent data directory
ARGS="--cfon --country $country --bind 127.0.0.1:$port --cache-dir $cache_dir"
EOF
}

# Create Systemd Service
create_service() {
    local port="$1"
    local service_name="psiphon-${port}"
    local env_file="${CONFIG_DIR}/psiphon-${port}.env"
    local log_file="${LOG_DIR}/${service_name}.log"
    
    cat > "${SYSTEMD_DIR}/${service_name}.service" << EOF
[Unit]
Description=Psiphon Proxy Service - Port $port
Documentation=https://github.com/bepass-org/warp-plus
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=$WARP_DIR
EnvironmentFile=$env_file

# Clean cache on start to prevent identity issues
ExecStartPre=/bin/bash -c 'rm -rf \${CACHE_DIR}/primary || true'

# Start with arguments from EnvironmentFile
ExecStart=$WARP_BIN \$ARGS

# Reliable restart policy
Restart=always
RestartSec=60
StartLimitInterval=600
StartLimitBurst=3

# Logging
StandardOutput=append:$log_file
StandardError=append:$log_file

[Install]
WantedBy=multi-user.target
EOF
}

# Deploy Function
deploy() {
    check_dependencies
    install_warp_plus
    
    mkdir -p "$CONFIG_DIR" "$LOG_DIR"
    
    SERVER_COUNTRY=$(get_server_country)
    echo -e "${BLUE}Server Country: $SERVER_COUNTRY (will exclude from selection)${NC}"
    
    read -rp "Number of instances (1-10) [Default: 10]: " count
    count=${count:-10}
    [[ ! "$count" =~ ^[0-9]+$ ]] && count=10
    
    # Process Countries
    AVAILABLE_COUNTRIES=$(echo "$VALID_COUNTRIES" | tr ' ' '\n' | grep -v "^${SERVER_COUNTRY}$" | tr '\n' ' ')
    RANDOM_COUNTRIES=($(echo "$AVAILABLE_COUNTRIES" | tr ' ' '\n' | shuf | head -n $count))
    
    echo -e "${GREEN}Deploying $count instances...${NC}"
    
    for ((i=0; i<count; i++)); do
        port=$((8080 + i))
        country="${RANDOM_COUNTRIES[$i]}"
        
        echo -e "  [Port $port] Country: ${BOLD}$country${NC}"
        
        create_env_file "$port" "$country"
        create_service "$port"
        
        systemctl daemon-reload
        systemctl enable "psiphon-${port}" --quiet
    done
    
    # Staggered Start
    echo ""
    echo -e "${YELLOW}Starting services (staggered delay: 35s)...${NC}"
    for ((i=0; i<count; i++)); do
        port=$((8080 + i))
        echo -ne "  Starting psiphon-${port}... "
        systemctl restart "psiphon-${port}"
        echo -e "${GREEN}✓${NC}"
        
        if ((i < count - 1)); then
            sleep 35
        fi
    done
    
    echo -e "${GREEN}Deployment Complete!${NC}"
    echo -e "Check status: ./check-psiphon.sh"
}

# Status Function
status() {
    echo ""
    printf "%-10s %-10s %-15s %-10s\n" "PORT" "STATUS" "IP" "COUNTRY"
    echo "------------------------------------------------"
    
    # Find all psiphon env files
    for env in "${CONFIG_DIR}"/psiphon-*.env; do
        [[ ! -f "$env" ]] && continue
        
        # Source the env file to get config variables
        source "$env"
        
        svc_status="STOPPED"
        if systemctl is-active --quiet "psiphon-${PORT}"; then
            svc_status="ACTIVE"
            ip_info=$(curl -s --connect-timeout 3 --socks5 127.0.0.1:$PORT https://ipapi.co/json 2>/dev/null)
            if [[ -n "$ip_info" ]]; then
                ip=$(echo "$ip_info" | jq -r .ip 2>/dev/null)
                real_country=$(echo "$ip_info" | jq -r .country_code 2>/dev/null)
                if [[ "$ip" != "null" ]]; then
                    svc_status="ONLINE"
                fi
            fi
        fi
        
        printf "%-10s %-10s %-15s %-10s\n" "$PORT" "$svc_status" "${ip:- -}" "${real_country:- -}"
    done
    echo ""
}

# Wrapper
case "$1" in
    status) status ;;
    *) deploy ;;
esac
